# Generated by Django 3.0.6 on 2020-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='comunidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='elevacion',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
